// <auto-generated />
namespace Hiperion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserHasRoles20150514daltamirano : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserHasRoles20150514daltamirano));
        
        string IMigrationMetadata.Id
        {
            get { return "201505141848076_UserHasRoles-20150514-daltamirano"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
