// <auto-generated />
namespace Hiperion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Roles20150512daltamirano : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Roles20150512daltamirano));
        
        string IMigrationMetadata.Id
        {
            get { return "201505122051446_Roles-20150512-daltamirano"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
